import React from 'react';
import {
  Document, Page, Text, View, StyleSheet, pdf,
} from '@react-pdf/renderer';
import type { ResearchReport } from './types';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a2e' },
  header: { marginBottom: 20, borderBottomWidth: 2, borderBottomColor: '#6366f1', paddingBottom: 12 },
  title: { fontSize: 22, fontWeight: 'bold', color: '#1a1a2e', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#6b7280' },
  summary: { fontSize: 10, lineHeight: 1.6, color: '#374151', marginBottom: 16, padding: 12, backgroundColor: '#f3f4f6', borderRadius: 4 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#1a1a2e', marginTop: 16, marginBottom: 8, borderBottomWidth: 1, borderBottomColor: '#e5e7eb', paddingBottom: 4 },
  text: { fontSize: 10, lineHeight: 1.6, color: '#374151', marginBottom: 6 },
  finding: { fontSize: 10, color: '#374151', marginBottom: 4, paddingLeft: 12 },
  findingBullet: { flexDirection: 'row', marginBottom: 4 },
  bullet: { width: 12, fontSize: 10, color: '#6366f1' },
  metricRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  metricLabel: { fontSize: 9, color: '#6b7280' },
  metricValue: { fontSize: 9, fontWeight: 'bold', color: '#1a1a2e' },
  companyInfo: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  companyField: { padding: 6, backgroundColor: '#f3f4f6', borderRadius: 4, minWidth: 120 },
  companyFieldLabel: { fontSize: 8, color: '#6b7280', marginBottom: 2 },
  companyFieldValue: { fontSize: 9, fontWeight: 'bold', color: '#1a1a2e' },
  swotGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  swotQuadrant: { width: '48%', padding: 8, borderRadius: 4, marginBottom: 4 },
  swotTitle: { fontSize: 10, fontWeight: 'bold', marginBottom: 4 },
  swotItem: { fontSize: 8, color: '#374151', marginBottom: 2 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#9ca3af', borderTopWidth: 1, borderTopColor: '#e5e7eb', paddingTop: 8 },
  metricsBar: { flexDirection: 'row', justifyContent: 'space-around', padding: 10, backgroundColor: '#eef2ff', borderRadius: 4, marginBottom: 16 },
  metricBox: { alignItems: 'center' },
  metricBoxValue: { fontSize: 14, fontWeight: 'bold', color: '#4f46e5' },
  metricBoxLabel: { fontSize: 7, color: '#6b7280', marginTop: 2 },
});

const ReportPdf: React.FC<{ report: ResearchReport }> = ({ report }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>{report.title}</Text>
        <Text style={styles.subtitle}>
          Generated by Carelwave AI Research Engine · {new Date().toLocaleDateString()}
        </Text>
      </View>

      {/* Metrics bar */}
      <View style={styles.metricsBar}>
        <View style={styles.metricBox}>
          <Text style={styles.metricBoxValue}>{report.metrics.agents_used}</Text>
          <Text style={styles.metricBoxLabel}>Agents</Text>
        </View>
        <View style={styles.metricBox}>
          <Text style={styles.metricBoxValue}>{report.metrics.total_sources}</Text>
          <Text style={styles.metricBoxLabel}>Sources</Text>
        </View>
        <View style={styles.metricBox}>
          <Text style={styles.metricBoxValue}>{report.metrics.facts_extracted}</Text>
          <Text style={styles.metricBoxLabel}>Facts</Text>
        </View>
        <View style={styles.metricBox}>
          <Text style={styles.metricBoxValue}>{(report.metrics.total_ms / 1000).toFixed(1)}s</Text>
          <Text style={styles.metricBoxLabel}>Time</Text>
        </View>
        {report.confidence_score && (
          <View style={styles.metricBox}>
            <Text style={styles.metricBoxValue}>{Math.round(report.confidence_score.overall * 100)}%</Text>
            <Text style={styles.metricBoxLabel}>Confidence</Text>
          </View>
        )}
      </View>

      {/* Summary */}
      <View style={styles.summary}>
        <Text>{report.summary}</Text>
      </View>

      {/* Company Profile */}
      {report.company_profile && (
        <View>
          <Text style={styles.sectionTitle}>Company Profile</Text>
          <View style={styles.companyInfo}>
            {report.company_profile.name && (
              <View style={styles.companyField}>
                <Text style={styles.companyFieldLabel}>Company</Text>
                <Text style={styles.companyFieldValue}>{report.company_profile.name}</Text>
              </View>
            )}
            {report.company_profile.industry && (
              <View style={styles.companyField}>
                <Text style={styles.companyFieldLabel}>Industry</Text>
                <Text style={styles.companyFieldValue}>{report.company_profile.industry}</Text>
              </View>
            )}
            {report.company_profile.ceo && (
              <View style={styles.companyField}>
                <Text style={styles.companyFieldLabel}>CEO</Text>
                <Text style={styles.companyFieldValue}>{report.company_profile.ceo}</Text>
              </View>
            )}
            {report.company_profile.market_cap && (
              <View style={styles.companyField}>
                <Text style={styles.companyFieldLabel}>Market Cap</Text>
                <Text style={styles.companyFieldValue}>{report.company_profile.market_cap}</Text>
              </View>
            )}
          </View>
        </View>
      )}

      {/* Key Findings */}
      {report.key_findings && report.key_findings.length > 0 && (
        <View>
          <Text style={styles.sectionTitle}>Key Findings</Text>
          {report.key_findings.map((finding, i) => (
            <View key={i} style={styles.findingBullet}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.finding}>{finding}</Text>
            </View>
          ))}
        </View>
      )}

      {/* Financial Data */}
      {report.financial_data && report.financial_data.length > 0 && (
        <View>
          <Text style={styles.sectionTitle}>Financial Data</Text>
          {report.financial_data.map((metric, i) => (
            <View key={i} style={styles.metricRow}>
              <Text style={styles.metricLabel}>{metric.label}</Text>
              <Text style={styles.metricValue}>
                {typeof metric.value === 'number' ? metric.value.toFixed(2) : metric.value} {metric.unit}
              </Text>
            </View>
          ))}
        </View>
      )}

      {/* SWOT Analysis */}
      {report.swot_analysis && (
        <View>
          <Text style={styles.sectionTitle}>SWOT Analysis</Text>
          <View style={styles.swotGrid}>
            {(['strengths', 'weaknesses', 'opportunities', 'threats'] as const).map((quadrant) => (
              <View
                key={quadrant}
                style={[
                  styles.swotQuadrant,
                  {
                    backgroundColor:
                      quadrant === 'strengths' ? '#ecfdf5' :
                      quadrant === 'weaknesses' ? '#fef2f2' :
                      quadrant === 'opportunities' ? '#eff6ff' :
                      '#fffbeb',
                  },
                ]}
              >
                <Text style={styles.swotTitle}>
                  {quadrant.charAt(0).toUpperCase() + quadrant.slice(1)}
                </Text>
                {report.swot_analysis![quadrant].slice(0, 4).map((item, i) => (
                  <Text key={i} style={styles.swotItem}>• {item}</Text>
                ))}
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Sections */}
      {report.sections.map((section, i) => (
        <View key={i} wrap={false}>
          <Text style={styles.sectionTitle}>{section.title}</Text>
          <Text style={styles.text}>{section.content.slice(0, 2000)}</Text>
        </View>
      ))}

      {/* Footer */}
      <Text style={styles.footer} fixed render={({ pageNumber, totalPages }) =>
        `Carelwave AI Research Report · Confidential · Page ${pageNumber} of ${totalPages}`
      } />
    </Page>
  </Document>
);

export async function downloadReportAsPdf(report: ResearchReport) {
  const blob = await pdf(<ReportPdf report={report} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${report.title.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}_report.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}
